on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Releasing rmb
    # we use 18.04 to be compatible with libc version on zos
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev musl-tools
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
          sudo unzip -d /usr/local protoc-21.12-linux-x86_64.zip
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        name: Build release
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/rmb-relay
            target/x86_64-unknown-linux-musl/release/rmb-peer
